# Generated by Django 5.1.3 on 2024-11-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('slug', models.SlugField(default='')),
                ('imagen', models.ImageField(upload_to='images/post')),
            ],
        ),
    ]
